In [3]:
import scipy
import scipy.io
import numpy as np

In [5]:
R = scipy.io.loadmat('demo_robust_L2_out.nips.10.R.mat')['M']

In [6]:
print(R)

[[  5.59958739e-03   2.37303116e+00   0.00000000e+00   6.08329653e-01
    4.28867196e+00   0.00000000e+00   1.01745984e-01   0.00000000e+00
    1.32043084e-01   9.13878687e-01]
 [  4.39827781e-01   2.61665156e-03   1.11244288e-01   3.31003589e-01
    2.11580694e-01   8.13662552e-03   8.71432272e-02   5.42675608e-03
    1.02696948e-01   8.50565093e-02]
 [  0.00000000e+00   2.22479758e+00   2.01227760e+03   1.18788907e+00
    1.99061705e+02   5.89539685e+01   1.26514493e+00   2.82001540e+01
    1.39982181e+01   1.70582222e+02]
 [  1.60295794e-01   4.70583426e-01   8.44436560e-02   9.82041201e-01
    5.12283503e-01   4.00527103e-01   4.45285088e-02   3.98527532e-01
    4.38645388e-03   4.64846772e+00]
 [  3.55048355e+00   9.45064605e-01   4.44590722e+01   1.60950343e+00
    3.53665475e+02   9.43884332e+00   1.23231267e+00   8.20037187e+00
    5.11329202e+00   3.78994587e+01]
 [  0.00000000e+00   4.19786326e-02   1.52084243e+01   1.45348965e+00
    1.09022786e+01   4.66985634e+00   4.62378

In [8]:
print(type(R))

<class 'numpy.ndarray'>


In [11]:
np.sum(R, axis=1)

array([  8.42330012e+00,   1.38473307e+00,   2.48775170e+03,
         7.70608490e+00,   4.66113877e+02,   5.57743107e+01,
         3.99971699e+00,   6.27798079e+01,   3.41427361e+00,
         5.68506686e+02])

In [12]:
R[1, 3]

0.33100358935341534

In [13]:
np.all(R>0)

False

In [15]:
x = np.arange(25).reshape((5, 5))
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [16]:
np.all(x > 0)

False

In [19]:
y = np.arange(1, 26).reshape((5, 5))
print(y)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [20]:
np.all(y > 0)

True